/// <reference types="react" />
  import { ComponentType, SVGAttributes } from 'react';

  interface Props extends SVGAttributes<SVGElement> {
    color?: string;
    size?: string | number;
  }

  type Icon = ComponentType<Props>;
  export const IconAUp: Icon;
export const IconARight: Icon;
export const IconMainnet: Icon;
export const IconALeft: Icon;
export const IconADown: Icon;
export const IconColorShare: Icon;
export const IconShareW: Icon;
export const IconFaucet: Icon;
export const IconQuestion: Icon;
export const IconEdit: Icon;
export const IconArrowDown: Icon;
export const IconArrowUp: Icon;
export const IconArrowLeft: Icon;
export const IconArrowRight: Icon;
export const IconClose: Icon;
export const IconArrowD: Icon;
export const IconArrowU: Icon;
export const IconColorBtc: Icon;
export const IconColorEth: Icon;
export const IconColorUsdc: Icon;
export const IconColorWbtc: Icon;
export const IconColorToken1: Icon;
export const IconColorToken0: Icon;
export const IconColorToastNor: Icon;
export const IconColorToastWarning: Icon;
export const IconColorToastLoading: Icon;
export const IconColorToastSuccess: Icon;
export const IconColorToastFail: Icon;
export const IconCopy: Icon;
export const IconColorMetamask: Icon;
export const IconSearch: Icon;
export const IconGuide: Icon;
export const IconKline: Icon;
export const IconShare: Icon;
export const IconMore: Icon;
export const IconChart: Icon;
export const IconDocs: Icon;
export const IconReport: Icon;
export const IconCode: Icon;
export const IconLauange: Icon;
export const IconTwitter: Icon;
export const IconMedium: Icon;
export const IconDiscord: Icon;
export const IconAudit: Icon;
export const IconTelegram: Icon;
export const IconGithub: Icon;
export const IconColorApeX: Icon;
export const IconColorEs: Icon;
export const IconColorVe: Icon;
export const IconTestnet: Icon;
export const IconDelete: Icon;
export const IconSettings: Icon;
export const IconBug: Icon;
export const IconGitbook: Icon;
export const IconFaq: Icon;
